### ISSUE TITLE
Server stops just after starting

### ISSUE THREAD

**Issue by PatrickSauts** [cdapio/netty-http#71]
I'm trying to use your project on a kotlin project but when I start the server it stops just after starting.
If I put a breakpoint on NettyHttpService:184 then I can use the server.
am I missing something ?

```kotlin
class Server {

	companion object {
		@JvmStatic
		fun main(args: Array<String>) {
			val handlers = ArrayList<HttpHandler>()
			handlers.add(AuthenticationController())
			val service = NettyHttpService.builder("the-app")
				.setPort(8080)
				.setHttpHandlers(handlers)
				.build()
			service.start()
		}
	}
```

**Comment by chtyim** [comment]
Hi Patrick,

The NettHttpService starts up background daemon threads to listen for incoming traffic. You do need to block your main thread in order to prevent the JVM to exit. The simplest you can do is something like this in Java (I am not familiar with the Kotlin language, but I believe you can do pretty much the same).

public class Server {
  public static void main(String[] args) throws Exception {
    NettyHttpService httpService = NettyHttpService.builder("the-app")
      .setPort(8080)
      .setHttpHandlers(new AuthenticationController())
      .build();

    CountDownLatch shutdownLatch = new CountDownLatch(1);
    httpService.start();
    Runtime.getRuntime().addShutdownHook(new Thread(() -> {
      try {
        httpService.stop();
      } catch (Exception e) {
        e.printStackTrace();
      } finally {
        shutdownLatch.countDown();
      }
    }));
    shutdownLatch.await();
  }
}

Terence


Terence Yim | Staff Software Engineer | terencey@google.com <mailto:terencey@google.com> |

**Comment by PatrickSauts** [comment]
Thank you Terence I had done a similar thing but I wasn't sure if it was intended.
I actually was expecting a join() after the start(), maybe it could be a good idea to add the code you mentioned in a join() method.
